# .github/workflows/minify.yaml

name: Minify JS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Minify JS
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'src'
          output: 'dist'
          overwrite: true

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'dist'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
